# Create a draft release to preview changelog without submitting production releases
name: Draft Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v.*(-alpha|-beta).*' # Tag push events, i.e. v1.0.0-alpha, v1.0.0-alpha.1 v1.0.1-beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Jirafy Changelog
        id: changelog
        uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jiraHost: ${{ secrets.JIRA_HOST }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          prerelease: false
